### PR TITLE
turkish language added

### PR DESCRIPTION
**Pull request by cobanov**

### CODE REVIEW

**Comment by TeaM-TL** [comment]
Hi Mert
many thanks for you translation, but please to fix it.
During translation you have to keep *msgid* (this is like ID to find string to replace your version), and add translation only in *msgstr*, eg.:
```
msgid "done"
msgstr "Gotowe"
```

**Review by TeaM-TL — CHANGES_REQUESTED** [review]
Hi Mert
many thanks for you translation, but please to fix it.
During translation you have to keep *msgid* (this is like ID to find string to replace your version), and add translation only in *msgstr*, eg.:
```
msgid "done"
msgstr "Gotowe"
```

**Comment by cobanov** [comment]
Hey, 

I fixed it.

**Review by TeaM-TL — APPROVED** [review]
great!

**Pull request merged**
